import { test, expect } from '@playwright/test';

test('case-validation', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('heading', { name: 'วางแผนการเงินเพื่อชีวิตหลังเกษียณ' }).click();
  await page.getByRole('textbox', { name: '1-' }).nth(1).click();
  await page.getByRole('textbox', { name: '1-' }).nth(1).click();
  await page.getByRole('textbox', { name: '1-' }).nth(1).fill('730');
  await page.getByText('สูงสุดได้ไม่เกิน').click();
  await page.locator('div').filter({ hasText: /^ปัจจุบันคุณอายุ$/ }).getByPlaceholder('1-').click();
  await page.locator('div').filter({ hasText: /^ปัจจุบันคุณอายุ$/ }).getByPlaceholder('1-').fill('30');
  await page.getByRole('textbox', { name: '1-' }).nth(2).click();
  await page.getByRole('textbox', { name: '1-' }).nth(2).press('ArrowRight');
  await page.getByRole('textbox', { name: '1-' }).nth(2).fill('90');
  await page.locator('div').filter({ hasText: /^ต้องการเกษียณเมื่ออายุอายุเกษียณต้องน้อยกว่าหลังเกษียณต้องการใช้เงินจนถึงอายุ$/ }).getByRole('paragraph').click();
  await page.getByText('อายุเกษียณต้องน้อยกว่าหลังเกษียณต้องการใช้เงินจนถึงอายุ').nth(1).click();
  await page.getByRole('textbox', { name: '1-' }).nth(1).click();
  await page.getByRole('textbox', { name: '1-' }).nth(1).click();
  await page.locator('div').filter({ hasText: /^ต้องการเกษียณเมื่ออายุ$/ }).getByPlaceholder('1-').click();
  await page.locator('div').filter({ hasText: /^ต้องการเกษียณเมื่ออายุ$/ }).getByPlaceholder('1-').fill('60');
  await page.getByRole('textbox', { name: '1-' }).nth(3).click();
  await page.getByRole('textbox', { name: '1-' }).nth(3).click();
  await page.getByRole('textbox', { name: '1-' }).nth(3).fill('59');
  await page.locator('div').filter({ hasText: /^ต้องการเกษียณเมื่ออายุ$/ }).getByPlaceholder('1-').click();
  await page.locator('div').filter({ hasText: /^ต้องการเกษียณเมื่ออายุอายุเกษียณต้องน้อยกว่าหลังเกษียณต้องการใช้เงินจนถึงอายุ$/ }).getByRole('paragraph').click();
  await page.locator('div').filter({ hasText: /^หลังเกษียณต้องการใช้เงินจนถึงอายุ$/ }).getByPlaceholder('1-').click();
  await page.getByText('อายุเกษียณต้องน้อยกว่าหลังเกษียณต้องการใช้เงินจนถึงอายุ').nth(1).click();
  await page.locator('div').filter({ hasText: /^หลังเกษียณต้องการใช้เงินจนถึงอายุ$/ }).getByPlaceholder('1-').click();
  await page.locator('div').filter({ hasText: /^หลังเกษียณต้องการใช้เงินจนถึงอายุ$/ }).getByPlaceholder('1-').fill('90');
  await page.getByRole('button', { name: 'ต่อไป' }).click();
  await page.locator('div').filter({ hasText: /^เงินออมมีเงินออมไว้แล้ว$/ }).getByPlaceholder('0-').click();
  await page.getByRole('textbox', { name: '0-100' }).click();
  await page.getByRole('textbox', { name: '0-100' }).fill('5');
  await page.getByText('%การออมเพิ่มขึ้นปีละ ต้องน้อยกว่า/เท่ากับ ผลตอบแทนต่อปีที่คาดหวัง').click();
  await page.getByRole('textbox', { name: '0-100' }).click();
  await page.getByRole('textbox', { name: '0-100' }).fill('45');
  await page.getByRole('textbox', { name: '0-100' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: '0-100' }).fill('0');
  await page.getByRole('textbox', { name: '0.1-' }).click();
  await page.getByRole('textbox', { name: '0.1-' }).fill('0');
  await page.getByText('อยู่ระหว่าง 0.1 ถึง').click();
  await page.getByRole('textbox', { name: '0.1-' }).click();
  await page.getByRole('textbox', { name: '0.1-' }).fill('0.1');
  await page.locator('div').filter({ hasText: /^กองทุนสำรองเลี้ยงชีพจำนวนเงินสะสมในกองทุนสำรองเลี้ยงชีพ ณ ปัจจุบัน$/ }).getByPlaceholder('0-').click();
  await page.getByRole('textbox', { name: '-50,000,000' }).click();
  await page.getByRole('textbox', { name: '-50,000,000' }).fill('6,000,0000');
  await page.getByText('สูงสุดได้ไม่เกิน').click();
  await page.getByRole('textbox', { name: '-50,000,000' }).click();
  await page.getByRole('textbox', { name: '-50,000,000' }).fill('0,000,000');
  await page.getByRole('textbox', { name: '-500,000' }).click();
  await page.getByRole('textbox', { name: '-500,000' }).fill('60,0000');
  await page.getByText('สูงสุดได้ไม่เกิน').click();
  await page.getByRole('textbox', { name: '-500,000' }).click();
  await page.getByRole('textbox', { name: '-500,000' }).fill('00,000');
  await page.getByRole('button', { name: 'คำนวณ' }).click();
  await page.getByText('47,819 บาท').first().click();
  await page.getByText('34,829 บาท').click();
  await page.getByText('17,476,290 บาท').nth(1).click();
  await page.getByText('- บาท').click();
  await page.getByRole('paragraph').filter({ hasText: /^47,819 บาท$/ }).click();
});